global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["xd.cdtfc.com.cn:9090"]
  - job_name: "go_app_server"
    static_configs:
      - targets:
          - "xd.cdtfc.com.cn:9999"
